export interface SessionTitles {
  en?: string
  zh?: string
}

export interface SessionSummaries {
  en?: string
  zh?: string
}

export interface ParsedSummary {
  /** Bilingual task titles from the leading front-matter, or null. */
  titles: SessionTitles | null
  /** Bilingual Markdown bodies, or null for legacy single-language summaries. */
  summaries?: SessionSummaries | null
  /**
   * Compatibility body for callers that have not adopted locale selection.
   * New bilingual summaries prefer English; legacy summaries remain unchanged.
   */
  body: string
  /** True when a raw front-matter title exceeded the 96-character contract. */
  titleOverflow?: boolean
}

export const SUMMARY_TITLE_CHAR_LIMIT = 96
export type SummaryTitleKey = 'title' | 'title_zh'

export interface SummaryTitleRepair {
  summary: string
  shortened: SummaryTitleKey[]
  /** Normalized, unbounded titles from the source document. */
  sourceTitles: SessionTitles | null
}

interface SummarySourceLine {
  content: string
  ending: string
}

interface LeadingSummaryFrontMatter {
  lines: SummarySourceLine[]
  closing: number
}

const SUMMARY_SECTION_START_RE = /^<!--\s*spool:summary:(en|zh)\s*-->$/
const SUMMARY_SECTION_END = '<!-- /spool:summary -->'

/**
 * Summaries generated by the local agent start with a small front-matter
 * block carrying bilingual task-outcome titles:
 *
 *     ---
 *     title: Fix daemon reconnect loop after macOS sleep/wake
 *     title_zh: 修复 macOS 休眠唤醒后 daemon 重连死循环
 *     ---
 *
 * The block is stored verbatim in the summary so shares round-trip
 * losslessly; readers parse it out at display/projection time. Only a
 * LEADING `---` block is treated as front-matter; unknown keys are ignored;
 * anything malformed degrades to `titles: null` with the original text as
 * the body.
 */
export function parseSummaryFrontMatter(summaryMd: string | null | undefined): ParsedSummary {
  const source = summaryMd ?? ''
  const frontMatter = leadingSummaryFrontMatter(source)
  if (!frontMatter) return withParsedSummaries(null, source, false)

  const titles: SessionTitles = {}
  let titleOverflow = false
  for (const line of frontMatter.lines.slice(1, frontMatter.closing)) {
    const title = parseSummaryTitleLine(line.content)
    if (!title) continue
    const locale = title.key === 'title' ? 'en' : 'zh'
    if (Array.from(title.value).length > SUMMARY_TITLE_CHAR_LIMIT) titleOverflow = true
    const value = boundTitle(title.value)
    if (!value) continue
    titles[locale] = value
  }

  const body = frontMatter.lines
    .slice(frontMatter.closing + 1)
    .map((line) => line.content)
    .join('\n')
    .replace(/^\s*\n/, '')

  return withParsedSummaries(titles.en || titles.zh ? titles : null, body, titleOverflow)
}

/**
 * Shorten only overlong leading front-matter titles while preserving every
 * other source byte, including mixed LF/CRLF line endings and both bodies.
 */
export function repairOverlongSummaryTitles(summary: string): SummaryTitleRepair {
  const frontMatter = leadingSummaryFrontMatter(summary)
  if (!frontMatter) return { summary, shortened: [], sourceTitles: null }

  const shortened: SummaryTitleKey[] = []
  const sourceTitles: SessionTitles = {}
  for (const line of frontMatter.lines.slice(1, frontMatter.closing)) {
    const title = parseSummaryTitleLine(line.content)
    if (!title) continue
    sourceTitles[title.key === 'title' ? 'en' : 'zh'] = title.value
    if (Array.from(title.value).length <= SUMMARY_TITLE_CHAR_LIMIT) continue
    line.content = `${title.key}: ${shortenSummaryTitle(title.value)}`
    shortened.push(title.key)
  }

  return {
    summary:
      shortened.length === 0
        ? summary
        : frontMatter.lines.map((line) => `${line.content}${line.ending}`).join(''),
    shortened,
    sourceTitles: sourceTitles.en || sourceTitles.zh ? sourceTitles : null,
  }
}

function leadingSummaryFrontMatter(source: string): LeadingSummaryFrontMatter | null {
  const lines = splitSummarySourceLines(source)
  if (lines[0]?.content.trim() !== '---') return null
  const closing = lines.findIndex((line, index) => index > 0 && line.content.trim() === '---')
  return closing === -1 ? null : { lines, closing }
}

function splitSummarySourceLines(source: string): SummarySourceLine[] {
  const lines: SummarySourceLine[] = []
  let start = 0
  while (start <= source.length) {
    const newline = source.indexOf('\n', start)
    if (newline === -1) {
      lines.push({ content: source.slice(start), ending: '' })
      break
    }
    const contentEnd = newline > start && source[newline - 1] === '\r' ? newline - 1 : newline
    lines.push({
      content: source.slice(start, contentEnd),
      ending: source.slice(contentEnd, newline + 1),
    })
    start = newline + 1
  }
  return lines
}

function parseSummaryTitleLine(line: string): { key: SummaryTitleKey; value: string } | null {
  const trimmed = line.trim()
  const separator = trimmed.indexOf(':')
  if (separator === -1) return null
  const candidate = trimmed.slice(0, separator).trimEnd()
  if (candidate !== 'title' && candidate !== 'title_zh') return null
  return { key: candidate, value: normalizeTitle(trimmed.slice(separator + 1)) }
}

/**
 * Canonical bilingual bodies are delimited with invisible Markdown comments:
 *
 *     <!-- spool:summary:en -->
 *     # English summary
 *     <!-- /spool:summary -->
 *
 *     <!-- spool:summary:zh -->
 *     # 中文摘要
 *     <!-- /spool:summary -->
 *
 * Exact line delimiters keep the format deterministic without exposing
 * localization plumbing in rendered Markdown. Any malformed or mixed body
 * safely falls back to the legacy single-language representation.
 */
function withParsedSummaries(
  titles: SessionTitles | null,
  body: string,
  titleOverflow: boolean,
): ParsedSummary {
  const summaries = parseSummarySections(body)
  return {
    titles,
    summaries,
    body: summaries?.en ?? summaries?.zh ?? body,
    titleOverflow,
  }
}

function parseSummarySections(body: string): SessionSummaries | null {
  const lines = body.split(/\r?\n/)
  const summaries: SessionSummaries = {}
  let index = 0
  let found = false

  while (index < lines.length && lines[index]!.trim() === '') index++
  while (index < lines.length) {
    const start = SUMMARY_SECTION_START_RE.exec(lines[index]!.trim())
    if (!start) return null
    const locale = start[1] as keyof SessionSummaries
    if (summaries[locale] !== undefined) return null
    found = true
    index++

    const section: string[] = []
    while (index < lines.length && lines[index]!.trim() !== SUMMARY_SECTION_END) {
      section.push(lines[index]!)
      index++
    }
    if (index >= lines.length) return null
    const value = section.join('\n').trim()
    if (!value) return null
    summaries[locale] = value
    index++
    while (index < lines.length && lines[index]!.trim() === '') index++
  }

  return found && summaries.en !== undefined && summaries.zh !== undefined ? summaries : null
}

function normalizeTitle(raw: string): string {
  const unquoted = raw.trim().replace(/^["']|["']$/g, '')
  return unquoted.replace(/\s+/g, ' ').trim()
}

function boundTitle(value: string): string {
  return Array.from(value).slice(0, SUMMARY_TITLE_CHAR_LIMIT).join('')
}

function shortenSummaryTitle(value: string): string {
  const budget = SUMMARY_TITLE_CHAR_LIMIT - 1
  const clipped = Array.from(value).slice(0, budget)
  const lastSpace = clipped.lastIndexOf(' ')
  const bounded = lastSpace >= Math.floor(budget / 2) ? clipped.slice(0, lastSpace) : clipped
  return `${bounded.join('').replace(/[\s\p{P}]+$/u, '')}…`
}
