export interface SessionTitles {
  en?: string
  zh?: string
}

export interface ParsedSummary {
  /** Bilingual task titles from the leading front-matter, or null. */
  titles: SessionTitles | null
  /** The summary with the front-matter block stripped. */
  body: string
}

const MAX_TITLE_CHARS = 96

/**
 * Summaries generated by the local agent start with a small front-matter
 * block carrying bilingual task-outcome titles:
 *
 *     ---
 *     title: Fix daemon reconnect loop after macOS sleep/wake
 *     title_zh: 修复 macOS 休眠唤醒后 daemon 重连死循环
 *     ---
 *
 * The block is stored verbatim in the summary so shares round-trip
 * losslessly; readers parse it out at display/projection time. Only a
 * LEADING `---` block is treated as front-matter; unknown keys are ignored;
 * anything malformed degrades to `titles: null` with the original text as
 * the body.
 */
export function parseSummaryFrontMatter(summaryMd: string | null | undefined): ParsedSummary {
  const source = summaryMd ?? ''
  const lines = source.split(/\r?\n/)
  if (lines[0]?.trim() !== '---') return { titles: null, body: source }

  let closing = -1
  for (let i = 1; i < lines.length; i++) {
    if (lines[i]!.trim() === '---') {
      closing = i
      break
    }
  }
  if (closing === -1) return { titles: null, body: source }

  const titles: SessionTitles = {}
  for (const line of lines.slice(1, closing)) {
    const match = /^([A-Za-z0-9_-]+)\s*:\s*(.*)$/.exec(line.trim())
    if (!match) continue
    const value = cleanTitle(match[2]!)
    if (!value) continue
    if (match[1] === 'title') titles.en = value
    else if (match[1] === 'title_zh') titles.zh = value
  }

  const body = lines
    .slice(closing + 1)
    .join('\n')
    .replace(/^\s*\n/, '')

  return {
    titles: titles.en || titles.zh ? titles : null,
    body,
  }
}

function cleanTitle(raw: string): string {
  const unquoted = raw.trim().replace(/^["']|["']$/g, '')
  const singleLine = unquoted.replace(/\s+/g, ' ').trim()
  return Array.from(singleLine).slice(0, MAX_TITLE_CHARS).join('')
}
