export interface SessionTitles {
  en?: string
  zh?: string
}

export interface SessionSummaries {
  en?: string
  zh?: string
}

export interface ParsedSummary {
  /** Bilingual task titles from the leading front-matter, or null. */
  titles: SessionTitles | null
  /** Bilingual Markdown bodies, or null for legacy single-language summaries. */
  summaries?: SessionSummaries | null
  /**
   * Compatibility body for callers that have not adopted locale selection.
   * New bilingual summaries prefer English; legacy summaries remain unchanged.
   */
  body: string
  /** True when a raw front-matter title exceeded the 96-character contract. */
  titleOverflow?: boolean
}

const MAX_TITLE_CHARS = 96
const SUMMARY_SECTION_START_RE = /^<!--\s*spool:summary:(en|zh)\s*-->$/
const SUMMARY_SECTION_END = '<!-- /spool:summary -->'

/**
 * Summaries generated by the local agent start with a small front-matter
 * block carrying bilingual task-outcome titles:
 *
 *     ---
 *     title: Fix daemon reconnect loop after macOS sleep/wake
 *     title_zh: 修复 macOS 休眠唤醒后 daemon 重连死循环
 *     ---
 *
 * The block is stored verbatim in the summary so shares round-trip
 * losslessly; readers parse it out at display/projection time. Only a
 * LEADING `---` block is treated as front-matter; unknown keys are ignored;
 * anything malformed degrades to `titles: null` with the original text as
 * the body.
 */
export function parseSummaryFrontMatter(summaryMd: string | null | undefined): ParsedSummary {
  const source = summaryMd ?? ''
  const lines = source.split(/\r?\n/)
  if (lines[0]?.trim() !== '---') return withParsedSummaries(null, source, false)

  let closing = -1
  for (let i = 1; i < lines.length; i++) {
    if (lines[i]!.trim() === '---') {
      closing = i
      break
    }
  }
  if (closing === -1) return withParsedSummaries(null, source, false)

  const titles: SessionTitles = {}
  let titleOverflow = false
  for (const line of lines.slice(1, closing)) {
    const match = /^([A-Za-z0-9_-]+)\s*:\s*(.*)$/.exec(line.trim())
    if (!match) continue
    const locale = match[1] === 'title' ? 'en' : match[1] === 'title_zh' ? 'zh' : null
    if (locale === null) continue
    const normalized = normalizeTitle(match[2]!)
    if (Array.from(normalized).length > MAX_TITLE_CHARS) titleOverflow = true
    const value = boundTitle(normalized)
    if (!value) continue
    titles[locale] = value
  }

  const body = lines
    .slice(closing + 1)
    .join('\n')
    .replace(/^\s*\n/, '')

  return withParsedSummaries(titles.en || titles.zh ? titles : null, body, titleOverflow)
}

/**
 * Canonical bilingual bodies are delimited with invisible Markdown comments:
 *
 *     <!-- spool:summary:en -->
 *     # English summary
 *     <!-- /spool:summary -->
 *
 *     <!-- spool:summary:zh -->
 *     # 中文摘要
 *     <!-- /spool:summary -->
 *
 * Exact line delimiters keep the format deterministic without exposing
 * localization plumbing in rendered Markdown. Any malformed or mixed body
 * safely falls back to the legacy single-language representation.
 */
function withParsedSummaries(
  titles: SessionTitles | null,
  body: string,
  titleOverflow: boolean,
): ParsedSummary {
  const summaries = parseSummarySections(body)
  return {
    titles,
    summaries,
    body: summaries?.en ?? summaries?.zh ?? body,
    titleOverflow,
  }
}

function parseSummarySections(body: string): SessionSummaries | null {
  const lines = body.split(/\r?\n/)
  const summaries: SessionSummaries = {}
  let index = 0
  let found = false

  while (index < lines.length && lines[index]!.trim() === '') index++
  while (index < lines.length) {
    const start = SUMMARY_SECTION_START_RE.exec(lines[index]!.trim())
    if (!start) return null
    const locale = start[1] as keyof SessionSummaries
    if (summaries[locale] !== undefined) return null
    found = true
    index++

    const section: string[] = []
    while (index < lines.length && lines[index]!.trim() !== SUMMARY_SECTION_END) {
      section.push(lines[index]!)
      index++
    }
    if (index >= lines.length) return null
    const value = section.join('\n').trim()
    if (!value) return null
    summaries[locale] = value
    index++
    while (index < lines.length && lines[index]!.trim() === '') index++
  }

  return found && summaries.en !== undefined && summaries.zh !== undefined ? summaries : null
}

function normalizeTitle(raw: string): string {
  const unquoted = raw.trim().replace(/^["']|["']$/g, '')
  return unquoted.replace(/\s+/g, ' ').trim()
}

function boundTitle(value: string): string {
  return Array.from(value).slice(0, MAX_TITLE_CHARS).join('')
}
