/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 7159322891fab0325569ec04c68ea686)
interface __BaseEnv_CloudflareEnv {
	ORIGIN_BACKEND: "https://spool-share-backend-staging.pages.dev" | "https://spool-share-backend.pages.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface StagingEnv {
		ORIGIN_BACKEND: "https://spool-share-backend-staging.pages.dev";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORIGIN_BACKEND">> {}
}
