/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AtChar123handleChar125RouteImport } from './routes/@{$handle}'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as CliAuthRouteImport } from './routes/cli-auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MeRouteImport } from './routes/me'
import { Route as MySessionsRouteImport } from './routes/my-sessions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AtChar123handleChar125IndexRouteImport } from './routes/@{$handle}.index'
import { Route as AtChar123handleChar125ProjectSlugRouteImport } from './routes/@{$handle}.$projectSlug'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteConnectorsRouteImport } from './routes/_site.connectors'
import { Route as SiteDaemonRouteImport } from './routes/_site.daemon'
import { Route as SiteLogoLabRouteImport } from './routes/_site.logo-lab'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as SessionSidRouteImport } from './routes/session.$sid'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as SiteBlogIndexRouteImport } from './routes/_site.blog.index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site.blog.$slug'
import { Route as SiteDocsSplatRouteImport } from './routes/_site.docs.$'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects.$projectId.edit'

const AtChar123handleChar125Route = AtChar123handleChar125RouteImport.update({
  id: '/@{$handle}',
  path: '/@{$handle}',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli-auth',
  path: '/cli-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MySessionsRoute = MySessionsRouteImport.update({
  id: '/my-sessions',
  path: '/my-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123handleChar125IndexRoute =
  AtChar123handleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AtChar123handleChar125Route,
  } as any)
const AtChar123handleChar125ProjectSlugRoute =
  AtChar123handleChar125ProjectSlugRouteImport.update({
    id: '/$projectSlug',
    path: '/$projectSlug',
    getParentRoute: () => AtChar123handleChar125Route,
  } as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteConnectorsRoute = SiteConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDaemonRoute = SiteDaemonRouteImport.update({
  id: '/daemon',
  path: '/daemon',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLogoLabRoute = SiteLogoLabRouteImport.update({
  id: '/logo-lab',
  path: '/logo-lab',
  getParentRoute: () => SiteRoute,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSidRoute = SessionSidRouteImport.update({
  id: '/session/$sid',
  path: '/session/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDocsSplatRoute = SiteDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => SiteRoute,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/projects/$projectId/edit',
  path: '/projects/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/@{$handle}': typeof AtChar123handleChar125RouteWithChildren
  '/': typeof SiteIndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/explore': typeof ExploreRoute
  '/me': typeof MeRoute
  '/my-sessions': typeof MySessionsRoute
  '/privacy': typeof PrivacyRoute
  '/sessions': typeof SessionsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/@{$handle}/$projectSlug': typeof AtChar123handleChar125ProjectSlugRoute
  '/connectors': typeof SiteConnectorsRoute
  '/daemon': typeof SiteDaemonRoute
  '/logo-lab': typeof SiteLogoLabRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/projects/new': typeof ProjectsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/session/$sid': typeof SessionSidRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/@{$handle}/': typeof AtChar123handleChar125IndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/docs/$': typeof SiteDocsSplatRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/blog/': typeof SiteBlogIndexRoute
}
export interface FileRoutesByTo {
  '/cli-auth': typeof CliAuthRoute
  '/explore': typeof ExploreRoute
  '/me': typeof MeRoute
  '/my-sessions': typeof MySessionsRoute
  '/privacy': typeof PrivacyRoute
  '/sessions': typeof SessionsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/@{$handle}/$projectSlug': typeof AtChar123handleChar125ProjectSlugRoute
  '/connectors': typeof SiteConnectorsRoute
  '/daemon': typeof SiteDaemonRoute
  '/logo-lab': typeof SiteLogoLabRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/projects/new': typeof ProjectsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/session/$sid': typeof SessionSidRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/@{$handle}': typeof AtChar123handleChar125IndexRoute
  '/': typeof SiteIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/docs/$': typeof SiteDocsSplatRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/blog': typeof SiteBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/@{$handle}': typeof AtChar123handleChar125RouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/cli-auth': typeof CliAuthRoute
  '/explore': typeof ExploreRoute
  '/me': typeof MeRoute
  '/my-sessions': typeof MySessionsRoute
  '/privacy': typeof PrivacyRoute
  '/sessions': typeof SessionsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/@{$handle}/$projectSlug': typeof AtChar123handleChar125ProjectSlugRoute
  '/_site/connectors': typeof SiteConnectorsRoute
  '/_site/daemon': typeof SiteDaemonRoute
  '/_site/logo-lab': typeof SiteLogoLabRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/projects/new': typeof ProjectsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/session/$sid': typeof SessionSidRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/@{$handle}/': typeof AtChar123handleChar125IndexRoute
  '/_site/': typeof SiteIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/docs/$': typeof SiteDocsSplatRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/@{$handle}'
    | '/'
    | '/cli-auth'
    | '/explore'
    | '/me'
    | '/my-sessions'
    | '/privacy'
    | '/sessions'
    | '/sign-in'
    | '/terms'
    | '/@{$handle}/$projectSlug'
    | '/connectors'
    | '/daemon'
    | '/logo-lab'
    | '/blog/rss.xml'
    | '/projects/new'
    | '/s/$slug'
    | '/session/$sid'
    | '/teams/$teamId'
    | '/@{$handle}/'
    | '/projects/'
    | '/teams/'
    | '/blog/$slug'
    | '/docs/$'
    | '/projects/$projectId/edit'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cli-auth'
    | '/explore'
    | '/me'
    | '/my-sessions'
    | '/privacy'
    | '/sessions'
    | '/sign-in'
    | '/terms'
    | '/@{$handle}/$projectSlug'
    | '/connectors'
    | '/daemon'
    | '/logo-lab'
    | '/blog/rss.xml'
    | '/projects/new'
    | '/s/$slug'
    | '/session/$sid'
    | '/teams/$teamId'
    | '/@{$handle}'
    | '/'
    | '/projects'
    | '/teams'
    | '/blog/$slug'
    | '/docs/$'
    | '/projects/$projectId/edit'
    | '/blog'
  id:
    | '__root__'
    | '/@{$handle}'
    | '/_site'
    | '/cli-auth'
    | '/explore'
    | '/me'
    | '/my-sessions'
    | '/privacy'
    | '/sessions'
    | '/sign-in'
    | '/terms'
    | '/@{$handle}/$projectSlug'
    | '/_site/connectors'
    | '/_site/daemon'
    | '/_site/logo-lab'
    | '/blog/rss.xml'
    | '/projects/new'
    | '/s/$slug'
    | '/session/$sid'
    | '/teams/$teamId'
    | '/@{$handle}/'
    | '/_site/'
    | '/projects/'
    | '/teams/'
    | '/_site/blog/$slug'
    | '/_site/docs/$'
    | '/projects/$projectId/edit'
    | '/_site/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AtChar123handleChar125Route: typeof AtChar123handleChar125RouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  CliAuthRoute: typeof CliAuthRoute
  ExploreRoute: typeof ExploreRoute
  MeRoute: typeof MeRoute
  MySessionsRoute: typeof MySessionsRoute
  PrivacyRoute: typeof PrivacyRoute
  SessionsRoute: typeof SessionsRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SSlugRoute: typeof SSlugRoute
  SessionSidRoute: typeof SessionSidRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/@{$handle}': {
      id: '/@{$handle}'
      path: '/@{$handle}'
      fullPath: '/@{$handle}'
      preLoaderRoute: typeof AtChar123handleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-auth': {
      id: '/cli-auth'
      path: '/cli-auth'
      fullPath: '/cli-auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sessions': {
      id: '/my-sessions'
      path: '/my-sessions'
      fullPath: '/my-sessions'
      preLoaderRoute: typeof MySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/': {
      id: '/@{$handle}/'
      path: '/'
      fullPath: '/@{$handle}/'
      preLoaderRoute: typeof AtChar123handleChar125IndexRouteImport
      parentRoute: typeof AtChar123handleChar125Route
    }
    '/@{$handle}/$projectSlug': {
      id: '/@{$handle}/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/@{$handle}/$projectSlug'
      preLoaderRoute: typeof AtChar123handleChar125ProjectSlugRouteImport
      parentRoute: typeof AtChar123handleChar125Route
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/connectors': {
      id: '/_site/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof SiteConnectorsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/daemon': {
      id: '/_site/daemon'
      path: '/daemon'
      fullPath: '/daemon'
      preLoaderRoute: typeof SiteDaemonRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/logo-lab': {
      id: '/_site/logo-lab'
      path: '/logo-lab'
      fullPath: '/logo-lab'
      preLoaderRoute: typeof SiteLogoLabRouteImport
      parentRoute: typeof SiteRoute
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sid': {
      id: '/session/$sid'
      path: '/session/$sid'
      fullPath: '/session/$sid'
      preLoaderRoute: typeof SessionSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/docs/$': {
      id: '/_site/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof SiteDocsSplatRouteImport
      parentRoute: typeof SiteRoute
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AtChar123handleChar125RouteChildren {
  AtChar123handleChar125ProjectSlugRoute: typeof AtChar123handleChar125ProjectSlugRoute
  AtChar123handleChar125IndexRoute: typeof AtChar123handleChar125IndexRoute
}

const AtChar123handleChar125RouteChildren: AtChar123handleChar125RouteChildren =
  {
    AtChar123handleChar125ProjectSlugRoute:
      AtChar123handleChar125ProjectSlugRoute,
    AtChar123handleChar125IndexRoute: AtChar123handleChar125IndexRoute,
  }

const AtChar123handleChar125RouteWithChildren =
  AtChar123handleChar125Route._addFileChildren(
    AtChar123handleChar125RouteChildren,
  )

interface SiteRouteChildren {
  SiteConnectorsRoute: typeof SiteConnectorsRoute
  SiteDaemonRoute: typeof SiteDaemonRoute
  SiteLogoLabRoute: typeof SiteLogoLabRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteDocsSplatRoute: typeof SiteDocsSplatRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteConnectorsRoute: SiteConnectorsRoute,
  SiteDaemonRoute: SiteDaemonRoute,
  SiteLogoLabRoute: SiteLogoLabRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteDocsSplatRoute: SiteDocsSplatRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AtChar123handleChar125Route: AtChar123handleChar125RouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  CliAuthRoute: CliAuthRoute,
  ExploreRoute: ExploreRoute,
  MeRoute: MeRoute,
  MySessionsRoute: MySessionsRoute,
  PrivacyRoute: PrivacyRoute,
  SessionsRoute: SessionsRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SSlugRoute: SSlugRoute,
  SessionSidRoute: SessionSidRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
