name: Feature request
description: Suggest an idea
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: Describe the use case
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would the solution look like?
      placeholder: Describe your ideal outcome
