// The Spool birth record: the one Spool-generated record appended to a
// materialized (resumed) session. It is clearly marked as not being part of
// the original conversation, carries the source coordinates + workspace
// card for the agent to self-restore the codebase, and doubles as the
// lineage carrier — when a resumed session is later shared, the share
// pipeline extracts the machine block below to fill lineageJson.

export const BIRTH_OPEN = '<spool-resume-note>'
export const BIRTH_CLOSE = '</spool-resume-note>'
const BIRTH_JSON_OPEN = '<spool-birth-json>'
const BIRTH_JSON_CLOSE = '</spool-birth-json>'

export interface BirthPayload {
  source: {
    sid: string
    position: number
    url: string | null
  }
}

export function buildBirthText(payload: BirthPayload, cardJson: string | null): string {
  const lines = [
    BIRTH_OPEN,
    'This session was resumed via Spool from a shared session. This note was',
    'generated by Spool — it is not part of the original conversation.',
    '',
    `Source: ${payload.source.url ?? payload.source.sid} (@${payload.source.position})`,
    '',
    "Workspace card — the repo state last observed on the author's machine:",
    cardJson ?? '(no workspace card: restore degrades to conversation-only)',
    '',
    'Hint for the agent: if the codebase above is not present in the current',
    'directory, you can restore it yourself — clone the remote from the card,',
    'check out the recorded branch/commit. Your earlier edits and setup',
    'commands are all in this transcript. Uncommitted files listed as dirty',
    'cannot be restored from coordinates.',
    `${BIRTH_JSON_OPEN}${JSON.stringify(payload)}${BIRTH_JSON_CLOSE}`,
    BIRTH_CLOSE,
  ]
  return lines.join('\n')
}

/**
 * Scan record bodies for a birth record and recover its payload. Used by
 * `spool share` to set lineage on sessions that were themselves born from
 * a resume — the local store that would normally track lineage doesn't
 * exist yet in this PR.
 */
export function extractBirthPayload(recordBodies: readonly string[]): BirthPayload | null {
  for (const body of recordBodies) {
    // Cheap pre-filter on the raw line before paying for a parse.
    if (!body.includes(BIRTH_JSON_OPEN)) continue
    let parsed: unknown
    try {
      parsed = JSON.parse(body)
    } catch {
      continue
    }
    const text = findMarkedString(parsed)
    if (text === null) continue
    const open = text.indexOf(BIRTH_JSON_OPEN)
    const close = text.indexOf(BIRTH_JSON_CLOSE, open)
    if (open === -1 || close === -1) continue
    try {
      const decoded = JSON.parse(text.slice(open + BIRTH_JSON_OPEN.length, close)) as unknown
      if (isBirthPayload(decoded)) return decoded
    } catch {
      continue
    }
  }
  return null
}

/** Depth-first search for the string value carrying the birth marker. */
function findMarkedString(value: unknown): string | null {
  if (typeof value === 'string') {
    return value.includes(BIRTH_JSON_OPEN) ? value : null
  }
  if (Array.isArray(value)) {
    for (const item of value) {
      const found = findMarkedString(item)
      if (found !== null) return found
    }
    return null
  }
  if (typeof value === 'object' && value !== null) {
    for (const item of Object.values(value)) {
      const found = findMarkedString(item)
      if (found !== null) return found
    }
    return null
  }
  return null
}

function isBirthPayload(value: unknown): value is BirthPayload {
  if (typeof value !== 'object' || value === null) return false
  const source = (value as { source?: unknown }).source
  if (typeof source !== 'object' || source === null) return false
  const { sid, position } = source as { sid?: unknown; position?: unknown }
  return typeof sid === 'string' && typeof position === 'number'
}
