import { spawn } from 'node:child_process'

import { describe, expect, it, vi } from 'vite-plus/test'

import {
  detectLocalSummaryAgents,
  invocationArgs,
  runLocalSummaryAgent,
} from './local-summary-agent.js'

function shellProcess(source: string): typeof spawn {
  return ((_: string, args: readonly string[], options: Parameters<typeof spawn>[2]) =>
    spawn('/bin/sh', ['-c', source, 'spool-agent-test', ...args], options)) as typeof spawn
}

describe('detectLocalSummaryAgents', () => {
  it('reports only installed Claude and Codex CLIs in stable order', async () => {
    const resolve = vi.fn(async (name: string) =>
      name === 'codex' ? '/Users/test/bin/codex' : null,
    )

    await expect(detectLocalSummaryAgents(resolve)).resolves.toEqual([
      { id: 'codex', name: 'Codex CLI', path: '/Users/test/bin/codex' },
    ])
    expect(resolve.mock.calls.map(([name]) => name)).toEqual(['claude', 'codex'])
  })
})

describe('local Summary Agent invocations', () => {
  it('runs Claude non-interactively without tools, persistence, or custom hooks', () => {
    expect(invocationArgs('claude', '/tmp/summary.md')).toEqual([
      '--print',
      '--output-format',
      'text',
      '--permission-mode',
      'dontAsk',
      '--tools',
      '',
      '--no-session-persistence',
      '--safe-mode',
    ])
  })

  it('runs Codex ephemerally in a read-only sandbox and captures only its final message', () => {
    expect(invocationArgs('codex', '/tmp/summary.md')).toEqual([
      'exec',
      '--ephemeral',
      '--sandbox',
      'read-only',
      '--skip-git-repo-check',
      '--color',
      'never',
      '--output-last-message',
      '/tmp/summary.md',
      '-',
    ])
  })

  it('captures Claude text output from a stdin-driven process', async () => {
    const spawnProcess = shellProcess(`
set -eu
cat >/dev/null
printf '## Outcome\n\nGenerated by Claude.\n'
`)

    await expect(
      runLocalSummaryAgent(
        { id: 'claude', name: 'Claude Code', path: '/unused/claude' },
        'bounded transcript prompt',
        { timeoutMs: 2_000, spawnProcess },
      ),
    ).resolves.toBe('## Outcome\n\nGenerated by Claude.')
  })

  it('reads only the Codex final-message file', async () => {
    const spawnProcess = shellProcess(`
set -eu
output=''
while [ "$#" -gt 0 ]; do
  if [ "$1" = '--output-last-message' ]; then
    shift
    output="$1"
  fi
  shift
done
cat >/dev/null
printf 'progress that must be ignored\n'
printf '## Outcome\n\nGenerated by Codex.\n' > "$output"
`)

    await expect(
      runLocalSummaryAgent(
        { id: 'codex', name: 'Codex CLI', path: '/unused/codex' },
        'bounded transcript prompt',
        { timeoutMs: 2_000, spawnProcess },
      ),
    ).resolves.toBe('## Outcome\n\nGenerated by Codex.')
  })
})
